name: Conventional Prerelease

on:
  workflow_dispatch:
    inputs:
      bump_type:
        # https://github.com/lerna/lerna/blob/main/commands/version/README.md#semver-bump
        description: 'Lerna semantic bump type'
        required: true
        default: 'premajor'
      pre_id:
        # https://github.com/lerna/lerna/blob/main/commands/version/README.md#--preid
        description: 'Prerelease identifier'
        required: true
        default: 'beta'
      pre_dist_tag:
        # https://github.com/lerna/lerna/tree/main/commands/publish#--pre-dist-tag-tag
        description: 'NPM version tag'
        required: true
        default: 'next'

jobs:
  # Run tests
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [
            14.x, # current LTS
          ]
    steps:
      # Checkout git branch
      - uses: actions/checkout@master
      # Install node.js environment
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile
      # Run all tests
      - name: Test
        run: yarn run test

  # Conventional prerelease
  prerelease:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - uses: actions/checkout@master
        with:
          # Fetch the entire history
          fetch-depth: 0
      # Install node.js environment
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile
      # Build all packages
      - name: Build
        run: yarn run build
      # Publish packages
      - name: Publish
        # Using "--no-verify-access" flag since lerna at the moment does not support NPM "automation" tokens
        # https://github.com/lerna/lerna/issues/2788
        run: yarn lerna publish ${{ github.event.inputs.bump_type }} --conventional-prerelease --preid ${{ github.event.inputs.pre_id }} --pre-dist-tag ${{ github.event.inputs.pre_dist_tag }} --allow-branch '**/*' --create-release github --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
