name: Conventional Release

on:
  push:
    branches:
      - master

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - uses: actions/checkout@v2
      # Install node.js environment
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      # Cache node_modules - lerna recipe (busting only when yarn.lock change)
      # https://github.com/actions/cache/blob/main/examples.md#node---lerna
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile
      # Run all tests
      - name: Test
        run: yarn run test

  # Conventional release
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - uses: actions/checkout@v2
        with:
          # Fetch the entire history (needed for lerna versioning)
          # @see https://github.com/lerna/lerna/issues/2542
          fetch-depth: 0
      # Install node.js environment
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      # Cache node_modules - lerna recipe (busting only when yarn.lock change)
      # https://github.com/actions/cache/blob/main/examples.md#node---lerna
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
      # Configure git with the built-in token
      # (to push back the release updates: package.json's version, CHANGELOG etc.)
      - name: Configure Git & NPM
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile
      # Build all packages
      - name: Build
        run: yarn run build
      # Authenticate yarn towards registry.npmjs.org
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> .npmrc
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Publish packages
      - name: Publish
        # Using "--no-verify-access" flag since lerna at the moment does not support NPM "automation" tokens
        # https://github.com/lerna/lerna/issues/2788
        run: yarn lerna publish --no-private --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Deploy Chromatic
  chromatic:
    needs: release
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required (Chromatic needs the entire git history)
      # Install node.js environment
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      # Cache node_modules - lerna recipe (busting only when yarn.lock change)
      # https://github.com/actions/cache/blob/main/examples.md#node---lerna
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile
      # Build Storybook (chromaui action uses npm and cannot use hoisted dependencies from yarn workspaces)
      - name: Build Storybook
        run: yarn run build:storybook
      # Chromatic deployment
      - uses: chromaui/action@v1
        with:
          autoAcceptChanges: true # from the main branch: accept changes automatically
          exitOnceUploaded: true # from the main branch: do not fail the action once uploaded
          # ignoreLastBuildOnBranch: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: dist
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/storybook-react
