name: Simulate Release

on: workflow_dispatch

jobs:
  # Simulate version release
  simulate-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - uses: actions/checkout@v2
        with:
          # Fetch the entire history (needed for lerna versioning)
          # @see https://github.com/lerna/lerna/issues/2542
          fetch-depth: 0
      # Install node.js environment
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      # Cache node_modules (busting only when yarn.lock change)
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile
      # Authenticate yarn towards registry.npmjs.org
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> .npmrc
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Simulate lerna version
      - name: Simulate release version
        # Using "--no-verify-access" flag since lerna at the moment does not support NPM "automation" tokens
        # https://github.com/lerna/lerna/issues/2788
        run: yarn lerna publish from-package --no-git-tag-version --no-push --allow-branch '**/*' --no-private --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
